'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'

export interface EmailLogEntry {
  id: string
  subject: string
  recipient_count: number
  segment: Record<string, string> | null
  resend_id: string | null
  sent_at: string
  email_type: string
  recipient_email: string | null
  metadata: Record<string, string> | null
  html_body: string | null
}

interface Props {
  log: EmailLogEntry[]
}

const inputStyle: React.CSSProperties = {
  background: '#060A0E', border: '1px solid #1C2936', color: '#CDD6E0',
  padding: '7px 10px', fontSize: 10, fontFamily: '"JetBrains Mono", monospace',
  letterSpacing: '0.05em', outline: 'none', width: '100%', boxSizing: 'border-box',
}
const selStyle: React.CSSProperties = { ...inputStyle, color: '#7D8A97', cursor: 'pointer' }

const TYPE_BADGE: Record<string, { label: string; color: string }> = {
  broadcast:       { label: 'BROADCAST',    color: '#E8A020' },
  customer_signup: { label: 'CUSTOMER',     color: '#34D399' },
  vendor_signup:   { label: 'VENDOR',       color: '#2EA8FF' },
}

function fmtDate(s: string) {
  return new Date(s).toISOString().slice(0, 16).replace('T', ' ')
}

// ── Body preview modal ────────────────────────────────────────────────────────

function BodyModal({ entry, onClose }: { entry: EmailLogEntry; onClose: () => void }) {
  const badge = TYPE_BADGE[entry.email_type] ?? { label: entry.email_type.toUpperCase(), color: '#7D8A97' }

  return (
    <div
      onClick={onClose}
      style={{
        position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.75)', zIndex: 1000,
        display: 'flex', alignItems: 'center', justifyContent: 'center',
      }}
    >
      <div
        onClick={e => e.stopPropagation()}
        style={{
          background: '#0C1118', border: '1px solid #253040', width: '80vw', maxWidth: 900,
          maxHeight: '85vh', display: 'flex', flexDirection: 'column',
        }}
      >
        {/* Header */}
        <div style={{ padding: '16px 24px', borderBottom: '1px solid #1C2936', display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10, marginBottom: 6 }}>
              <span style={{ background: badge.color + '20', color: badge.color, fontSize: 8, letterSpacing: '0.2em', padding: '2px 8px', border: `1px solid ${badge.color}40` }}>
                {badge.label}
              </span>
              <span style={{ color: '#3D5065', fontSize: 9 }}>{fmtDate(entry.sent_at)}</span>
            </div>
            <div style={{ color: '#CDD6E0', fontSize: 13, fontWeight: 700 }}>{entry.subject}</div>
            {entry.recipient_email && (
              <div style={{ color: '#7D8A97', fontSize: 10, marginTop: 4 }}>To: {entry.recipient_email}</div>
            )}
            {entry.email_type === 'broadcast' && (
              <div style={{ color: '#7D8A97', fontSize: 10, marginTop: 4 }}>
                {entry.recipient_count} recipients
                {entry.segment ? ' · ' + (Object.entries(entry.segment).filter(([, v]) => v !== 'all').map(([k, v]) => `${k}=${v}`).join(' ') || 'ALL SEGMENTS') : ''}
              </div>
            )}
            {entry.metadata && (
              <div style={{ color: '#7D8A97', fontSize: 9, marginTop: 4 }}>
                {[entry.metadata.city, entry.metadata.locale?.toUpperCase()].filter(Boolean).join(' · ')}
              </div>
            )}
          </div>
          <button
            onClick={onClose}
            style={{ background: 'none', border: '1px solid #253040', color: '#7D8A97', padding: '4px 10px', fontFamily: '"JetBrains Mono", monospace', fontSize: 10, cursor: 'pointer' }}
          >
            CLOSE ×
          </button>
        </div>

        {/* Body */}
        <div style={{ flex: 1, overflow: 'auto', padding: 24 }}>
          {entry.html_body ? (
            <div style={{ background: '#fff', padding: 20 }} dangerouslySetInnerHTML={{ __html: entry.html_body }} />
          ) : (
            <div style={{ color: '#3D5065', fontSize: 10, letterSpacing: '0.15em', textAlign: 'center', paddingTop: 48 }}>
              {entry.email_type === 'broadcast' ? 'BODY UNAVAILABLE (SENT BEFORE ENCRYPTION WAS ENABLED)' : 'TEMPLATE EMAIL — BODY GENERATED BY REACT COMPONENT'}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}

// ── Tab button ─────────────────────────────────────────────────────────────────

function TabBtn({ active, label, count, onClick }: { active: boolean; label: string; count?: number; onClick: () => void }) {
  return (
    <button
      onClick={onClick}
      style={{
        background: active ? 'rgba(232,160,32,0.08)' : 'transparent',
        border: 'none', borderBottom: active ? '2px solid #E8A020' : '2px solid transparent',
        color: active ? '#E8A020' : '#3D5065',
        padding: '10px 20px', fontFamily: '"JetBrains Mono", monospace',
        fontSize: 9, letterSpacing: '0.2em', cursor: 'pointer',
      }}
    >
      {label}{count !== undefined ? ` (${count})` : ''}
    </button>
  )
}

// ── Row ────────────────────────────────────────────────────────────────────────

function Row({ entry, onClick, i }: { entry: EmailLogEntry; onClick: () => void; i: number }) {
  const badge = TYPE_BADGE[entry.email_type] ?? { label: entry.email_type.toUpperCase(), color: '#7D8A97' }

  return (
    <tr
      onClick={onClick}
      style={{
        borderBottom: '1px solid #111920',
        background: i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.012)',
        cursor: 'pointer',
      }}
      onMouseEnter={e => (e.currentTarget.style.background = 'rgba(232,160,32,0.04)')}
      onMouseLeave={e => (e.currentTarget.style.background = i % 2 === 0 ? 'transparent' : 'rgba(255,255,255,0.012)')}
    >
      <td style={{ padding: '10px 16px' }}>
        <span style={{ background: badge.color + '18', color: badge.color, fontSize: 8, letterSpacing: '0.15em', padding: '2px 7px', border: `1px solid ${badge.color}30` }}>
          {badge.label}
        </span>
      </td>
      <td style={{ padding: '10px 16px', color: '#CDD6E0', maxWidth: 260, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
        {entry.subject}
      </td>
      <td style={{ padding: '10px 16px', color: '#7D8A97', fontSize: 10, maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>
        {entry.recipient_email ?? (
          <span style={{ color: '#34D399', fontWeight: 700 }}>{entry.recipient_count} recipients</span>
        )}
      </td>
      <td style={{ padding: '10px 16px', color: '#7D8A97', fontSize: 9 }}>
        {entry.email_type === 'broadcast'
          ? entry.segment
            ? Object.entries(entry.segment).filter(([, v]) => v !== 'all').map(([k, v]) => `${k}=${v}`).join(' · ') || 'ALL'
            : 'ALL'
          : entry.metadata
            ? [entry.metadata.city, entry.metadata.locale?.toUpperCase()].filter(Boolean).join(' · ')
            : '—'
        }
      </td>
      <td style={{ padding: '10px 16px', color: '#3D5065', fontSize: 9, whiteSpace: 'nowrap' }}>
        {fmtDate(entry.sent_at)}
      </td>
      <td style={{ padding: '10px 16px' }}>
        <span style={{ color: '#3D5065', fontSize: 8, letterSpacing: '0.1em', border: '1px solid #1C2936', padding: '2px 8px' }}>
          VIEW
        </span>
      </td>
    </tr>
  )
}

// ── Main component ─────────────────────────────────────────────────────────────

export function EmailCenter({ log }: Props) {
  const router = useRouter()
  const [tab, setTab] = useState<'all' | 'broadcasts' | 'signups' | 'compose'>('all')
  const [selected, setSelected] = useState<EmailLogEntry | null>(null)
  const [form, setForm] = useState({ subject: '', html: '', type: 'all', city: 'all', locale: 'all', mode: 'broadcast' as 'single' | 'broadcast', to: '' })
  const [sending, setSending] = useState(false)
  const [result, setResult] = useState<{ ok: boolean; message: string } | null>(null)

  const broadcasts = log.filter(e => e.email_type === 'broadcast')
  const signups = log.filter(e => e.email_type !== 'broadcast')
  const visible = tab === 'all' ? log : tab === 'broadcasts' ? broadcasts : tab === 'signups' ? signups : []

  async function send() {
    if (!form.subject || !form.html) return
    if (form.mode === 'single' && !form.to) return
    setSending(true)
    setResult(null)

    const payload: Record<string, unknown> = {
      subject: form.subject,
      html: form.html,
      mode: form.mode,
    }
    if (form.mode === 'single') {
      payload.to = form.to
    } else {
      payload.segment = { type: form.type, city: form.city, locale: form.locale }
    }

    const res = await fetch('/api/admin/send', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json', 'X-Requested-With': 'XMLHttpRequest' },
      body: JSON.stringify(payload),
    })
    const json = await res.json()
    if (res.ok) {
      setResult({ ok: true, message: form.mode === 'single' ? `SENT TO ${form.to}` : `TRANSMITTED TO ${json.total} RECIPIENTS` })
      setForm(f => ({ ...f, subject: '', html: '', to: '' }))
      setTimeout(() => router.refresh(), 800)
    } else {
      setResult({ ok: false, message: `ERROR: ${json.error}` })
    }
    setSending(false)
  }

  return (
    <div>
      {selected && <BodyModal entry={selected} onClose={() => setSelected(null)} />}

      {/* Tabs */}
      <div style={{ display: 'flex', borderBottom: '1px solid #1C2936', marginBottom: 20 }}>
        <TabBtn active={tab === 'all'} label="ALL" count={log.length} onClick={() => setTab('all')} />
        <TabBtn active={tab === 'broadcasts'} label="BROADCASTS" count={broadcasts.length} onClick={() => setTab('broadcasts')} />
        <TabBtn active={tab === 'signups'} label="SIGNUPS" count={signups.length} onClick={() => setTab('signups')} />
        <TabBtn active={tab === 'compose'} label="+ COMPOSE" onClick={() => setTab('compose')} />
      </div>

      {/* Email log table */}
      {tab !== 'compose' && (
        <div style={{ background: '#0C1118', border: '1px solid #1C2936' }}>
          {visible.length === 0 ? (
            <div style={{ padding: '48px', textAlign: 'center', color: '#3D5065', fontSize: 10, letterSpacing: '0.2em' }}>
              {tab === 'signups' ? 'NO SIGNUP EMAILS LOGGED YET — NEW SIGNUPS WILL APPEAR HERE' :
               tab === 'broadcasts' ? 'NO BROADCASTS SENT YET — USE COMPOSE TO SEND YOUR FIRST' :
               'NO EMAILS LOGGED YET'}
            </div>
          ) : (
            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11 }}>
              <thead>
                <tr style={{ borderBottom: '1px solid #1C2936' }}>
                  {['TYPE', 'SUBJECT', 'TO / RECIPIENTS', 'SEGMENT / INFO', 'SENT', ''].map(h => (
                    <th key={h} style={{ textAlign: 'left', padding: '10px 16px', color: '#3D5065', fontSize: 9, letterSpacing: '0.2em', fontWeight: 'normal' }}>{h}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {visible.map((entry, i) => (
                  <Row key={entry.id} entry={entry} i={i} onClick={() => setSelected(entry)} />
                ))}
              </tbody>
            </table>
          )}
        </div>
      )}

      {/* Compose tab */}
      {tab === 'compose' && (
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          <div style={{ background: '#0C1118', border: '1px solid #1C2936', padding: '24px' }}>
            <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.2em', marginBottom: 24 }}>EMAIL CONFIGURATION</div>

            {/* Mode toggle: Single vs Broadcast */}
            <div style={{ marginBottom: 20 }}>
              <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.15em', marginBottom: 10 }}>MODE</div>
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 8 }}>
                <button
                  onClick={() => setForm(f => ({ ...f, mode: 'single' }))}
                  style={{
                    ...inputStyle,
                    textAlign: 'center', cursor: 'pointer', fontWeight: 700, letterSpacing: '0.15em',
                    background: form.mode === 'single' ? 'rgba(232,160,32,0.1)' : '#060A0E',
                    borderColor: form.mode === 'single' ? '#E8A020' : '#1C2936',
                    color: form.mode === 'single' ? '#E8A020' : '#3D5065',
                  }}
                >
                  SINGLE
                </button>
                <button
                  onClick={() => setForm(f => ({ ...f, mode: 'broadcast' }))}
                  style={{
                    ...inputStyle,
                    textAlign: 'center', cursor: 'pointer', fontWeight: 700, letterSpacing: '0.15em',
                    background: form.mode === 'broadcast' ? 'rgba(232,160,32,0.1)' : '#060A0E',
                    borderColor: form.mode === 'broadcast' ? '#E8A020' : '#1C2936',
                    color: form.mode === 'broadcast' ? '#E8A020' : '#3D5065',
                  }}
                >
                  BROADCAST
                </button>
              </div>
            </div>

            {/* Single: recipient email */}
            {form.mode === 'single' && (
              <div style={{ marginBottom: 16 }}>
                <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.15em', marginBottom: 8 }}>RECIPIENT EMAIL</div>
                <input value={form.to} onChange={e => setForm(f => ({ ...f, to: e.target.value }))} placeholder="recipient@example.com" style={inputStyle} />
              </div>
            )}

            {/* Broadcast: segment filters */}
            {form.mode === 'broadcast' && (
              <div style={{ marginBottom: 20 }}>
                <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.15em', marginBottom: 10 }}>TARGET SEGMENT</div>
                <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 8 }}>
                  {(['type', 'city', 'locale'] as const).map(key => (
                    <div key={key}>
                      <div style={{ color: '#1C2936', fontSize: 8, letterSpacing: '0.15em', marginBottom: 4 }}>{key.toUpperCase()}</div>
                      <select value={form[key]} onChange={e => setForm(f => ({ ...f, [key]: e.target.value }))} style={selStyle}>
                        <option value="all">ALL</option>
                        {key === 'type' && <><option value="vendor">VENDOR</option><option value="customer">CUSTOMER</option></>}
                        {key === 'city' && <><option value="douala">DOUALA</option><option value="yaounde">YAOUNDÉ</option><option value="other">OTHER</option></>}
                        {key === 'locale' && <><option value="en">EN</option><option value="fr">FR</option></>}
                      </select>
                    </div>
                  ))}
                </div>
              </div>
            )}

            <div style={{ marginBottom: 16 }}>
              <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.15em', marginBottom: 8 }}>SUBJECT LINE</div>
              <input value={form.subject} onChange={e => setForm(f => ({ ...f, subject: e.target.value }))} placeholder="Enter email subject..." style={inputStyle} />
            </div>

            <div style={{ marginBottom: 20 }}>
              <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.15em', marginBottom: 8 }}>MESSAGE BODY (HTML content inside Karu template)</div>
              <textarea
                value={form.html}
                onChange={e => setForm(f => ({ ...f, html: e.target.value }))}
                rows={12}
                placeholder="<p>Your message here...</p>&#10;&#10;The content will be wrapped in the Karu branded email template automatically."
                style={{ ...inputStyle, resize: 'vertical', verticalAlign: 'top', lineHeight: 1.6 }}
              />
              <div style={{ color: '#3D5065', fontSize: 8, marginTop: 6, letterSpacing: '0.1em' }}>
                ✓ CONTENT WILL BE WRAPPED IN KARU BRANDED TEMPLATE (LOGO + AMBER DIVIDER + FOOTER)
              </div>
            </div>

            {result && (
              <div style={{
                padding: '10px 12px', marginBottom: 16, fontSize: 10, letterSpacing: '0.1em',
                border: `1px solid ${result.ok ? '#34D399' : '#F05252'}`,
                color: result.ok ? '#34D399' : '#F05252',
                background: result.ok ? 'rgba(52,211,153,0.05)' : 'rgba(240,82,82,0.05)',
              }}>
                {result.message}
              </div>
            )}

            <button
              onClick={send}
              disabled={sending || !form.subject || !form.html || (form.mode === 'single' && !form.to)}
              style={{
                width: '100%',
                background: sending || !form.subject || !form.html ? '#1C2936' : '#E8A020',
                color: '#060A0E', border: 'none', padding: '13px 0',
                fontFamily: '"JetBrains Mono", monospace', fontSize: 10, fontWeight: 700,
                letterSpacing: '0.25em', cursor: sending ? 'not-allowed' : 'pointer', transition: 'background 0.2s',
              }}
            >
              {sending ? 'TRANSMITTING...' : form.mode === 'single' ? 'SEND EMAIL →' : 'SEND BROADCAST →'}
            </button>
          </div>

          <div style={{ background: '#0C1118', border: '1px solid #1C2936', padding: '24px' }}>
            <div style={{ color: '#3D5065', fontSize: 9, letterSpacing: '0.2em', marginBottom: 16 }}>TEMPLATE PREVIEW</div>
            {form.html ? (
              <div style={{ background: '#1C1208', padding: 16, minHeight: 200, border: '1px solid #3D2510' }}>
                <div style={{ textAlign: 'center', marginBottom: 16 }}>
                  <span style={{ fontSize: 24, fontWeight: 'bold', letterSpacing: 4, color: '#E8A020' }}>KARU</span>
                </div>
                <div style={{ height: 2, background: '#E8A020', marginBottom: 16 }} />
                <div style={{ color: '#F5EFE4', fontSize: 16, fontWeight: 'bold', marginBottom: 12 }}>{form.subject || 'Subject'}</div>
                <div style={{ color: '#F5EFE4', fontSize: 13, lineHeight: 1.7 }} dangerouslySetInnerHTML={{ __html: form.html }} />
                <div style={{ textAlign: 'center', marginTop: 20 }}>
                  <span style={{ background: '#E8A020', color: '#1C1208', padding: '8px 20px', fontSize: 11, fontWeight: 'bold' }}>Visit getkaru.io</span>
                </div>
                <div style={{ borderTop: '1px solid #3D2510', marginTop: 20, paddingTop: 12, textAlign: 'center', color: '#5C3A1E', fontSize: 10 }}>
                  © {new Date().getFullYear()} Karu · Douala & Yaoundé
                </div>
              </div>
            ) : (
              <div style={{ color: '#1C2936', fontSize: 10, padding: '48px 0', textAlign: 'center' }}>PREVIEW RENDERS HERE</div>
            )}
          </div>
        </div>
      )}
    </div>
  )
}
